### ISSUE TITLE
Implement function to mint and distribute tokens

### ISSUE THREAD

**Issue by EGreg** [Intercoin/NonFungibleTokenContract#11]
Simple function

```
function mintAndDistribute(int256[] tokenIds, address[] addresses)
```

it will just loop through and call `_mint`, which will fill mappings in both directions `token => owner` and `owner => index => token` and emit `Transfer` events.

Also make sure we implemented the Enumerable extension to NFT.

**Comment by artman325** [comment]
contract have implement IERC721EnumerableUpgradeable
also have mintAndDistribute function .
keepo in mind that _mint was overrode with ERC721Enumerable and transferhooks
