### ISSUE TITLE
Implement suffix

### ISSUE THREAD

**Issue by EGreg** [Intercoin/NonFungibleTokenContract#14]
Please add the ability to have a "suffix" in addition to "baseURI" of SeriesInfo. By default it is "".

Then in tokenURI, also append this suffix. So for example `.json`

**Comment by artman325** [comment]
done with [commit 5fec9f5243181cb950aad56c0c3c74d80c7bfcab](https://github.com/Intercoin/NonFungibleTokenContract/commit/5fec9f5243181cb950aad56c0c3c74d80c7bfcab)
