### ISSUE TITLE
Add percentage based commissions to series info

### ISSUE THREAD

**Issue by EGreg** [Intercoin/NonFungibleTokenContract#15]
Make constant `FRACTION = 100000`. Whenever we need fractions, we first multiply by the numerator and then divide by this denominator (always do division after multiplication). Remember you don't need to use SafeMath anymore!

Please add to `SeriesInfo` (but not SaleInfo) the field `commission` which will just be the numerator in the fraction (number between 0 and 100000). By default it is 0 (no commission).

Please also add a function `setCommission(seriesId, commission, recipient)`. In this case, if seriesId is 0, then commission is for all series, and only contract owner can call it. Otherwise, a series owner can call it for their own series that they own, and set a recipient for the commissions (could be themselves). They can clear it by calling setCommission(seriesId, 0, 0)

During buy(), if the address being paid is not already the series owner, then send the proportional commission to the series owner and contract owner, and the rest to the token owner. If buyer overpaid ETH more than price of token in SaleInfo, then refund buyer the rest.

For token transfers, we may use a different mechanism in the future (blocking transfers which didn't pay a fixed fee commission) but for buying through the contract itself, the series owner can set the commission for tokens that may be sold on other exchanges.

**Comment by artman325** [comment]
it's out of date and features have already prensent. like constant `FRACTION`, methods: `seriesInfo`, `setCommission`.
refund while calling `buy()`,
paying commissions while `buy()` to series owner.
etc
