### ISSUE TITLE
Some more text changes

### ISSUE THREAD

**Issue by EGreg** [Intercoin/NonFungibleTokenContract#16]
SaleInfo related:
token -> currency
amount -> price
addToSale -> putOnSale
AddedToSale -> PutOnSale
saleUntil -> onSaleUntil
Bought -> TokenBought

"can call only by owner" -> "only owner can call this"
"!onlyContractOrSeriesOwner" -> "only owner or author can call this"

**Comment by EGreg** [comment]
listOnSale -> putOnSale

**Comment by EGreg** [comment]
isExists -> exists

**Comment by EGreg** [comment]
salesInfo -> saleInfo

**Comment by artman325** [comment]
done with commit: [d31781760107ae60bc3b5656b9986b5c7e4f48ad](https://github.com/Intercoin/NonFungibleTokenContract/commit/d31781760107ae60bc3b5656b9986b5c7e4f48ad)
 
 can not find:
-  addToSale -> putOnSale
