### ISSUE TITLE
function signatures

### ISSUE THREAD

**Issue by EGreg** [Intercoin/NonFungibleTokenContract#17]
Please change them to the following:

```
// to prevent frontrunning by e.g. seller
buy(uint256 tokenId, uint256 price, bool safe) payable
buy(uint256 tokenId, address currency, uint256 price, bool safe)
```

Events:

```
Event SeriesSaleChanged (uint64 seriesId, SaleInfo info) <-- if removed from sale, then info has onSaleUntil = 0
```

**Comment by artman325** [comment]
it's some part of telegram chat. mb outdated.
To prevent frontrunning we used no noreentrant contract and check before any external call
Also 
- now we have `hookCount` param that obtained from NFTSafeHook
- event `Event SeriesSaleChanged (uint64 seriesId, SaleInfo info)` replaced for two events:
```
event SeriesPutOnSale(
        uint64 indexed seriesId, 
        uint256 price, 
        address currency, 
        uint64 onSaleUntil
    );

    event SeriesRemovedFromSale(
        uint64 indexed seriesId
    );
```

Plese reopen issue if neeed some fixes about that
