### ISSUE TITLE
Mint NFTs in a very specific way.

### ISSUE THREAD

**Issue by EGreg** [Intercoin/NonFungibleTokenContract#2]
Today, I have figured out the holy grail of minting NFTs, with all the following properties:

* **Secure.** No one can hack the prices and rules.
* **Gasless.** Mining fees are only paid when NFT is bought.
* **Cheap.** No need to check permits and signatures of meta-transactions.
* **Series.** Supports grouping NFTs into series, on the same contract.
* **Flexible.** Allows the NFT issuers to create all kinds of randomness and effects, even after selling it.
* **Harmony.** Integrates completely with the back end structures we use in our existing community apps.

## Background

The basic idea behind it is that the [ERC-721 token standard](https://eips.ethereum.org/EIPS/eip-721) defines `tokenId` to be a 256-bit integer, so we separate it into two parts: 64 bits for the `seriesId` and the remainder for the `index`. Then, the prices, owners and base of tokenURI can be set for large swaths of tokens by default, at once. Meanwhile, each token's index would be appended to the tokenURI, to form URIs such as `"https://yoursite.com/somebase?token=" + index` or `"https://yoursite.com/somebase/" + index`

To make this 256-bit `tokenId` harmonize with [Streams plugin](https://qbix.com/platform/guide/streams#fields) on our current web-based platform, tonight I've implemented the following two functions:

```
$hexString = Streams::toHexString($publisherId, $streamId);
// this we can get a tokenId = "0x..." for querying NFT info on the blockchain
list($publisherId, $streamIdPrefix) = Streams::fromHexString($tokenId); 
// we can then use this for querying the database, as follows:
->where(
    'publisherId' => $publisherId, 
    'streamName' => Db_Range('Assets/NFT/$streamIdPrefix', true, false, true);
)->limit(1);
```

Note that `$streamId` is the last segment of `$streamName`, which typically follows the `$streamType/$streamId` format. As long as `$streamId` are designed to not be longer than 24 characters, there will be exactly one stream found per token. (Otherwise, there might be a slight chance of a collision and you'd have to pick the first stream, hence the `limit(1)`.)

## NFT Contract

@artman325 [please refactor the contract as in this issue](https://github.com/Intercoin/NonFungibleTokenContract/issues/3).

**Comment by artman325** [comment]
was implemented in branch main_hardhat and will be merge into main soon.
Also this description aloso available in wiki [NFT-Addressing-Scheme](https://github.com/Intercoin/NonFungibleTokenContract/wiki/NFT-Addressing-Scheme)
