### ISSUE TITLE
Please fix everything to uint16

### ISSUE THREAD

**Issue by EGreg** [Intercoin/NonFungibleTokenContract#23]
We had several places where user has to send uint256 to seriesId in external parameters. It was an oversight.

In next version of deployed NFTContract let's fix it. Find these places and make the correct size.

**Comment by artman325** [comment]
64bits are reserved for seriesId
so tokenID consist from seriesId(64 bits) and pure tokenId (192 bits)
total is **uint256**
i will turn it type in every method's param
