### ISSUE TITLE
err msg via delegate call can not handle

### ISSUE THREAD

**Issue by artman325** [Intercoin/NonFungibleTokenContract#29]
example if some try to mintAndDistribute (validation inside nftState.sol) didn't any revert (and do nothing. it's a plus)
need to fix and cat ch error messages

**Comment by artman325** [comment]
error messsages exists . it happens in other situation.  but need double check

**Comment by EGreg** [comment]
did you fix it @artman325

**Comment by EGreg** [comment]
if you did then close it @artman325

**Comment by artman325** [comment]
closed as an expired and will verify in next versions
