### ISSUE TITLE
Implement Safe Hooks

### ISSUE THREAD

**Issue by EGreg** [Intercoin/NonFungibleTokenContract#4]
*Safe Hooks*. Please modify the `_beforeTokenTransfer` hook to call, in order, the method `_beforeTokenTransfer(address(this), from, to, tokenId,)` on each smart contract listed in the array `beforeTokenTransferHooks`.  It starts empty, but it can contain, for example, requirements to pay a commission. If any of those hooks reverts, then `_beforeTokenTransfer` should throw an error like "Transfer Not Authorized". That means people will be able to write code in the future, that will enforce commissions, and not put it in this current contract.

Make a method `pushTokenTransferHook(seriesId, contractAddress)` that `onlyOwner` can call. At the end of this function, please set `seriesInfo[seriesId].hookCount = array.length;` and later when a token is minted, copy this `hookCount` into `TokenInfo.hookCount` Now this is what makes the hooks safe for owners of tokens (from e.g. using up all the gas): during `_transfer` of individual tokens, the only hooks that will execute were the ones that were there when the token was first minted. If `onlyOwner` guy later added more hooks, the `hookCount` on the `TokenInfo` will still be the same, so the new transfer hooks would not execute for anyone who already owns a token. So the token's owner isn't surprised with more restrictions later (added by contract owner or series owner). But someone who is buying + minting token *after* the hook was added, has to live with that hook too, on transfer.

**Comment by artman325** [comment]
implemented in [commit](https://github.com/Intercoin/NonFungibleTokenContract/commit/6eec154aba5b1c7ff8fac54cfe1e09c4626fb457)
- contract owner can add hook in for certain series
- every time when token minted,  contract will remember how many hook was activated. any further hooks will not be applied to such tokens. Only those that were active at the time of creation
- contract hooks can not be removed from the list
- method `transferHook` in hook contract must return true or false. if returned false - whole transfer will reverted
