### ISSUE TITLE
Implement external contracts acting as Sellers

### ISSUE THREAD

**Issue by EGreg** [Intercoin/NonFungibleTokenContract#5]
This is very similar to `approve(operator, tokenId)` and `setApprovalForAll(address, status)` except it can be done for series. So what is the point? Well, this way we can let any external contract (such as an auction) run, and then when there is a winner, this contract will be the approved caller, to mint the token to that specific winner. We can have many types of sales, this way. So please add `address SeriesInfo.seller` to the struct. In "simple" sales it is `0x0` by default. In sales done by an external smart contract, the series owner will set `seller` to that smart contract.

In any case, whenever a token is transferred, its `onSaleUntil` must be set to 0. Putting a token on sale for a long time, just put a really high timestamp many years into the future.

Note that owner of a series can call `erc721.setApprovalForAll(operator, status)` and this will also make the `operator` able to move all their tokens, across all the series. This is a second way, to allow external contracts such as auctions.

*Also note that auctions can be canceled by seller anytime (I checked and OpenSea does it that way). So just keep in mind, later on, we do auction contract, when receiving payments, it must check every time if token is still `forSaleUntil > block.time` and auction is either `isApprovedForAll()` for `ownerOf(token)` or a `seller` of that specific series. If it is not, it will just cancel the auction (refund money that is currently held, and also refuse to take money of current bidder, and just can). We will also have method to cancel the auction by anyone, which will check these conditions and cancel.*

**Comment by artman325** [comment]
we decided to avoid from seller and approval. instead this owner(deployer) should call setSeriesInfo and set author in seriesInfo tuple.
