### ISSUE TITLE
NFTSalesContract and NFTSalesFactory

### ISSUE THREAD

**Issue by EGreg** [Intercoin/NonFungibleTokenContract#60]
**PURCHASING TOKENS FOR SPECIAL PRICE**

First, make a NFTSalesFactory that produces instances. The parameters for producing an instance will include `owner, currency, price, beneficiary, duration`. The currency is an ERC20 token or `0x0` which represents the native coin. 

Make a NFTSalesContract for selling NFTs powered by NonFungibleTokenContract instances

It will have an `owner`, and methods `transferOwnership` and `renounceOwnership` (the `Ownable` interface). The owner will also have `whitelistAdd` and `whitelistRemove` methods, and `whitelist[address] = true ` mapping. It will have `whitelistOnly` modifier that checks if someone is on the whitelist.

It will have a `specialPurchase` function buy() that acts similarly to `distribute` function found in [bulkContract](https://etherscan.io/address/0x75f8a9e5c410c4d443ec72e1e4703e1fee61dc21) that you wrote

It will proxy call @mintAndDistribute@ on the smart contract

    /**
    * expects:
    * - all tokenIds belong to the same series and owner for each token able to primary sale (token owner == address(0))
    */
    function specialPurchase(
        address NFTcontract,
        uint256[] memory tokenIds, 
        address[] memory addresses
    ) 
        public 
        payable
        whitelistedOnly

The price per NFT will actually be set by the factory, in parameters when this instance is produced.

The @specialPurchase@ function will check the `currency` and either check the `msg.value` or allowance that `sender` has given to `this`. Then it will loop through the tokens and for each one, try to transfer its amount to `beneficiary`, but if is `0x0`, then send instead to the author of the NFT series.

In this case, you don't even need to get the info of the NFT series if `price` and `beneficiary` are not 0x0.

**LOCKING TOKENS**

Duration: If nonzero, then you will actually be transferring the NFT tokens to the instance itself, rather than the addresses. However, you will save the locked tokenIds to addresses, as follows:

 `public locked[tokenId] = struct { address: address, untilTimestamp: block.timestamp + duration }`

(please pack 160 + 32 bits into one slot, no need to take two slots here)

make a function `remainingDays(tokenId)` that simply returns `(timestamp - block.timestamp) / 86400`

and also make a function `distributeUnlockedTokens(tokenIds)` that can be called by any user, to distribute unlocked tokens to the appropriate addresses, if timestamp hasn't occurred yet, revert if "Tokens can be claimed after N more days." Where you encodepacked the error from N and two surrounding strings, first calculating N = remainingDays(tokenId). (This error may be misleading as the other tokens may be locked up for even longer, but probably they've all been purchased at same time.)

Also implement `claim(tokenIds)` that will claim them and send them to a the tx.origin (or msg.sender) address, which has to exactly match what was in the `locked` mapping for all of them, or it will revert. This is just for regular users to claim their tokenIds easily.

**Comment by artman325** [comment]
the main goal are to replace bulk contract on NftSales which will do the following
- take fee for  primarysale
- locked up for certain period (and do claim in further when period passed)
-  NftSales will be contract owner of NoneFungibleTokenContract and call mintAndDistribute for free
Q1: is it correct? please confirm this!

Also
how bulk contract worked:
- Deployer have created NoneFungibleTokenContract and NFTBulkSale
- make NFTBulkSale as an owner of NoneFungibleTokenContract
- User1 put series on sale for 5$ per item
- if User2 will buy token via NFTbuy: user1 send 5$ to NoneFungibleTokenContract  an obtain nft token
- if User2 will buy token/tokens via NFTBulkSale: user1 send 5$ to NFTBulkSale, NFTBulkSale send 5$ to author of series and then distribute nft token to User2. 
from NoneFungibleTokenContract side: tokens will be minted for free by contract owner!!!

so 
Q2: which tokens NftSales will sell to user? users-tokens or series-tokens?
what if series-author change price?

**Comment by artman325** [comment]
**Q3: in cases with NFTSales (NFTBulksale ) mintAndDistribute calls can happens via TrustedForwarder. so even if persons is in whitelist they can mint tokens from any series. is contract should to approve user mint only from certain series?**
