### ISSUE TITLE
Turn SalesContract into an NFT contract itself

### ISSUE THREAD

**Issue by EGreg** [Intercoin/NonFungibleTokenContract#77]
## The main idea

The Sales contract will own some NFTs until they can be claimed. On OpenSea, it has to be customizable. In order for that to happen it must actually *be* an NFT contract, and its `owner` has to claim it on OpenSea, by logging in with their private key.

So when `_distribute` happens it will mint its own NFTs with same or similar tokenURI as the NFT contract. And when `_claim` happens, it will burn those NFTs.

All these claim NFTs might or might not be transferred.

## Steps to do

It should simply inherit the following implementations from OpenZeppelin:

https://docs.openzeppelin.com/contracts/4.x/api/token/erc721#IERC721
https://docs.openzeppelin.com/contracts/4.x/api/token/erc721#IERC721Metadata
https://docs.openzeppelin.com/contracts/4.x/api/token/erc721#IERC721Enumerable

Also in its init `params` it should now take `name` and `symbol`. If empty, will put "NFT VAULT", "VAULT".
Copy `setBaseURI`, `baseURI` and `setSuffix`, `suffix` functions.

Basically, you can almost have NFT contract and NFTSales contract both inherit from same NFTBase contract, but maybe just copypaste because you will be overriding some of the OpenZeppelin methods below.

But in OpenZeppelin implementation, change `_owners[tokenId]` to be `pending[tokenIds[i]].recipient` [here](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v4.8.0/contracts/token/ERC721/ERC721.sol#L380), [here](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v4.8.0/contracts/token/ERC721/ERC721.sol#L217), [here](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v4.8.0/contracts/token/ERC721/ERC721.sol#L303), [here](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v4.8.0/contracts/token/ERC721/ERC721.sol#L380) and [here](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v4.8.0/contracts/token/ERC721/ERC721.sol#L337) -- in this last one, you should actually delete  the whole`pending[tokenId]`. It is a 160-bit address and it shares the slot with the `untilTimestamp` 64-bit timestamp.

In `params`, add `bool allowTransfers`. If true, then NFTs from this Sales contract can be transferred. By default, they can't, so any call to `_transfer` will throw error `NoTransfersAllowed()`.

It seems by the way that `claim()` is useless since `distributeUnlockedTokens()` does the same thing but can be called by anybody. But that's fine, whatever.

## Minting and Burning

In NFTSales, the `tokenURI` will be same as in `NFT`, but use its own `baseURI` and `suffix`. However, if `baseURI` is empty, it will actually call `tokenURI` on the NFT contract and return that instead!! (So, by default, unless we override the `baseURI` it will basically return the same exact `tokenURI` as the NFT contract. And it can work with any NFT contract that has `tokenURI` method).

The function `_distribute` calls [doMintAndDistribute](https://github.com/Intercoin/NonFungibleTokenContract/blob/main_aliens/contracts/sales/NFTSales.sol#L461) and after this, it should actually `_mint()` the NFT with same `tokenId`, to the recipient who can `_claim` it later. And during `_claim(tokenIds, shouldCheckOwner)` it should burn NFTs with those `tokenIds`.

So on NFT marketplaces, this SalesContract itself will appear as an NFT contract and the owner can put whatever metadata he wants on it. While the `name` and `symbol` in Etherscan will appear as well.

**Comment by EGreg** [comment]
Please check the result @artman325

**Comment by artman325** [comment]
just write here to understand what happens in contract
1. NFTContract add NFTSalesFactory as trustedforwarder. NFTSales Instances, which creates by NFTSalesFactory, can be able to mint any tokens in NFTContract through NFTSalesFactory with own price/currency.
So NFTSales is a just proxy contract.

2. NFTSales works in two modes:
- (if duration == 0) when tokens(NFTContract) immediately minted to user 
- (if duration != 0) when tokens(NFTContract) minted to NFTSales, user obtains VAULT token instead. after duration passed, user(or anyone if call distributeUnlockedTokens) can claim and VAULT token is burn

so this task is about second mode with duration != 0

**Comment by artman325** [comment]
> Also in its init params it should now take name and symbol. If empty, will put "NFT VAULT", "VAULT".

We can't specify a symbol and name for vault tokens. it's generate the following
"VAULT FOR {name}"
"{symbol}_VAULT"

> Copy setBaseURI, baseURI and setSuffix, suffix functions.

we do not copy, we inherit such functions. so if nftcontract' owner change baseuri, vault token baseuri will changed too without any custom uri, suffix, etc.

**Comment by artman325** [comment]
all already done except `allowTransfers` error .
it was fixed in #85
