### ISSUE TITLE
NFT testing

### ISSUE THREAD

**Issue by EGreg** [Intercoin/NonFungibleTokenContract#81]
platforms:

MetaMask mobile
TrustWallet mobile
AlphaWallet mobile
Polygonscan

blockchains:

BNB
Polygon

features:
Title
Description
URL in description link?
URL in token metadata link?
Image
Video
Embedded HTML page?

**Comment by artman325** [comment]
deployed tests nft contracts on  bnb, polygon
bnb - **0xdc922272dd005327f105043fe9101590ba08dace**
polygon - **0x7e6dadb326740b41a02f93bc8ffef574aaa2a3d0**

the table below will represent attributes accross metadata in json (the same for bsc and polygon)
more screens in http://intercoin.app/abs/results

**_the table will be updating_**
<table>
<tr>
<th></th>
<th></th>
<th>name</th>
<th>image</th>
<th>animation_url</th>
<th>external_link</th>
</tr>
<tr>
<td rowspan="4"><a href="https://intercoin.app/abs/0.json">0.json</a></td>
<td>AlpaWallet</td>
<td>+</td>
<td>+</td>
<td>+</td>
<td>+</td>
</tr>
<tr>
<td>TrustWallet</td>
<td>+</td>
<td>+</td>
<td>+</td>
<td>-</td>
</tr>
<tr>
<td>Metamask</td>
<td>-</td>
<td>-</td>
<td>-</td>
<td>-</td>
</tr>
<tr>
<td>OpenSea</td>
<td>+</td>
<td>+</td>
<td>+</td>
<td>-</td>
</tr>
</table>
