### ISSUE TITLE
Changing onlyOwner to signature's checking

### ISSUE THREAD

**Issue by SolidityNinja** [Intercoin/NonFungibleTokenContract#9]
In the current implementation only owner (deployer) of the contract is able to call setSeriesInfo() function, hence, if a user wants to create series, the deployer must pay gas for it. In case if a lot of users apply for creation, there will be huge waste of many for the deployer.  

In order to avoid it, we can make setSeriesInfo() function permissionless but change its signature and add `bytes calldata signature` to the list of its parameters. Inside of this function signature will be checked via  `_verifySigner(uint256 seriesId, SerieInfo memory info, bytes calldata signature)`, which will check if ECDSA.recover(keccak256(message), signature) is owner's address.

**Comment by artman325** [comment]
out of date
